name: Nuitka compiling linux

on:
  pull_request:
    branches:
      - develop
  push:
    #add more branches when trying out stuff
    branches:
      - main

jobs:
  linux:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python_version:
            - '3.9'
        python_main_file:
            - 'main'
    name: Ubuntu Python ${{ matrix.python_version }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install Nuitka and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install chrpath gdb ccache libfuse2
          python -m pip install nuitka
          python -m pip install .


      - name: Compile the source code with nuitka
        run: |
            python -m nuitka --gdb python_mp3/${{ matrix.python_main_file }}.py  --follow-imports

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: python_mp3-linux.zip
          path: |
              ${{ matrix.python_main_file }}.bin